const roleType = {
    ERROR: 'ERROR',
    FIND_ALL: 'FIND_ALL',
    SAVE: 'SAVE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    FIND_ONE_BY_ID: 'FIND_ONE_BY_ID',
    FIND_ALL_AND_PAGED: 'FIND_ALL_AND_PAGED',
    SET_FLAG_ACTION: 'SET_FLAG_ACTION',
    SET_ACTIVE_ID: 'SET_ACTIVE_ID',
}

export default roleType